#spring:
#  data:
#    mongodb:
#      host: monako.dev.eldorado.ru
#      port: 27017
#      database: test
#      username: myTester
#      password: xyz123
##      authentication-database: admin
##      uri: mongodb://myTester:xyz123@monako.dev.eldorado.ru:27017/test
